nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - 80:80
    links:
      - php
    volumes_from:
      - php
    environment:
      - VIRTUAL_HOST=api.smartex,www.api.smartex
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

php:
    container_name: php
    build: ./php/
    expose:
      - 9000
    volumes:
      - ./www:/var/www/html
    links:
      - redis
    restart: always

redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always